version: '3'

services:
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      - APP_SERVER_PORT=${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/server
      - ./client:/client
    command: yarn run dev
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
      - ${REACT_APP_WEBSOCKET_PORT}:${REACT_APP_WEBSOCKET_PORT}
    volumes:
      - ./client:/client
    links:
      - server
    command: yarn run start    

    